#!/bin/sh

avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -e -U flash:w:maker.hex:i
avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U eeprom:w:maker.eep
avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U lfuse:w:0xe2:m
sleep 1
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U hfuse:w:0xde:m
avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U hfuse:w:0xd4:m
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U lfuse:r:low:r
#avrdude -p t24 -c stk500 -P /dev/ttyUSB0 -U hfuse:r:high:r


